name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up jdk 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: make gradlew executable
        run: chmod +x gradlew

      - name: build
        run: ./gradlew build

      - name: assemble release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./gradlew assembleRelease

      - name: upload release apk
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk